HS-175 Convert REST API server to BFF component with GraphQL support
OpenNMS/horizon-stream pull request #136
Opened 2022-06-29 19:48 UTC by yangli2014

## JIRA Link
https://issues.opennms.org/browse/HS-175

## Checklist
* [ ] JIRA has been updated to 'in review'.
* [ ] Unit tests have been added as part of the PR.
* [ ] Manual tests have been completed, and notes added to JIRA.
* [ ] Details have been provided to docs team (if necessary)
* [ ] Screenshot(s) included (applicable to changes with a visual impact).

## Details of the change

- The Alarms and Events Rest API endpoints still exist. The API doc can be accessed at http://localhost:9090/swagger-ui/index.html
- The GraphQL schema and playground can be accessed at http://localhost:9090/gui
- The Nginx API gateway is configured to point to the API server.

2022-06-30 13:10 UTC, yangli2014 commented
> 

As we discussed I will address it in HS-210

2022-07-04 13:39 UTC, geraldhumphries requested changes
Feels really good seeing a PR that removes so much code :)

2022-07-04 13:39 UTC, geraldhumphries commented on platform/events/api/src/main/java/org/opennms/horizon/events/xml/DateTimeAdapter.java
> +
We should at least log something on exception here.

2022-07-04 15:54 UTC, yangli2014 commented on platform/events/api/src/main/java/org/opennms/horizon/events/xml/DateTimeAdapter.java
> +
Sure. The code here is handle the date in timestamp or ISO string format.

2022-07-04 20:12 UTC, yangli2014 commented on platform/events/api/src/main/java/org/opennms/horizon/events/xml/DateTimeAdapter.java
> +
After I cleaned up, this change is not needed anymore.

2022-07-05 13:46 UTC, geraldhumphries approved these changes

2022-07-07 14:02 UTC, mfrazier63 approved these changes
Looks much better!

2022-07-07 20:47 UTC, merged