HS-137: EditorConfig and PR template changes
OpenNMS/horizon-stream pull request #147
Opened 2022-07-11 22:54 UTC by geraldhumphries

## JIRA Link
https://issues.opennms.org/browse/HS-137

## Checklist
* [x] JIRA has been updated to 'in review'.
* [ ] Unit tests have been added as part of the PR.
* [ ] Manual tests have been completed, and notes added to JIRA.
* [x] Details have been provided to docs team (if necessary)
* [ ] Screenshot(s) included (applicable to changes with a visual impact).

## Details of the change
Adds an EditorConfig file and updates the PR template to match what we decided as part of HS-137.

2022-07-12 15:32 UTC, emarsh1995 requested changes
Looks good so far! I would suggest also pulling some elements from the PR template we have for Horizon Classic (for example, https://github.com/OpenNMS/opennms/pull/4962).

2022-07-12 15:32 UTC, emarsh1995 commented on .github/pull_request_template.md
> +<!-- Describe this pull request, what it changes, and why it's necessary -->
```suggestion
<!-- Describe this Pull Request, what it changes, and why it's necessary. -->
```

2022-07-12 15:32 UTC, emarsh1995 commented on .github/pull_request_template.md
> +## Jira Issue(s)
```suggestion
## Jira link(s)
```

2022-07-12 15:32 UTC, emarsh1995 commented on .github/pull_request_template.md
> +<!-- Flag things as "needs a close look" for reviewers, if necessary -->
```suggestion
<!-- Flag things as "needs a close look" for reviewers, if necessary. Include as much detail as possible (line numbers, concerns, and so on). -->
```

2022-07-12 15:32 UTC, emarsh1995 commented on .github/pull_request_template.md
> +* [ ] Jira issue(s) have been updated to "in review".
```suggestion
* [ ] Jira issue(s) have been updated to "In Review".
```

2022-07-12 15:32 UTC, emarsh1995 commented on .github/pull_request_template.md
> +* [ ] Includes appropriate tests.
This might need to be expanded upon, unless it's common knowledge among contributors.

2022-07-12 15:32 UTC, emarsh1995 commented on .github/pull_request_template.md
> +* [ ] Documentation has been updated, if necessary.
```suggestion
* [ ] Documentation has been updated as necessary.
```

2022-07-12 16:12 UTC, mikewrosey commented on .editorconfig
> +tab_width = 2
Should we add a rule for .ts and .js files? we use the same as .vue

2022-07-12 16:36 UTC, geraldhumphries commented on .github/pull_request_template.md
> +* [ ] Includes appropriate tests.
Would it be a good idea to link to the specific section in the wiki?

2022-07-12 16:38 UTC, geraldhumphries commented on .editorconfig
> +tab_width = 2
Good idea. This file is just an export of IntelliJ's default code style as EditorConfig with IJ-specific extensions disabled. There's a lot we can/should explicitly define like that.

2022-07-12 18:35 UTC, emarsh1995 commented on .github/pull_request_template.md
> +* [ ] Includes appropriate tests.
It might be, yes. Especially because, as the testing suite gets built out, the wiki will be expanded upon. :)

2022-07-13 19:26 UTC, yangli2014 commented on .github/pull_request_template.md
> +* [ ] Documentation has been updated, if necessary.
I suggest adding optional test instruction, in case some PR test is not easy to figure out.

2022-07-14 20:29 UTC, geraldhumphries commented on .github/pull_request_template.md
> +* [ ] Includes appropriate tests.
Added the link. Test strategy is not fully fleshed out yet, btw.

2022-07-14 20:29 UTC, geraldhumphries commented on .editorconfig
> +end_of_line = lf
Done

2022-07-14 20:38 UTC, emarsh1995 approved these changes
LGTM! :)

2022-07-15 14:49 UTC, merged