HS-191: Schedule Monitors and store time series data
OpenNMS/horizon-stream pull request #191
Opened 2022-08-02 13:40 UTC by cgorantla

## Description
Add monitors that schedule ICMP/SNMP periodically
Add ManagementIP to device
Adding device should trigger event that would schedule monitor

## Jira link(s)
- https://issues.opennms.org/browse/HS-191

## Checklist
* [x] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [x] Appropriate reviewer(s) have been selected.
* [x] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.

2022-08-02 15:38 UTC, yangli2014 commented on platform/db/dao-api/src/main/java/org/opennms/horizon/db/dao/api/IpInterfaceDao.java
>  import java.net.InetAddress;
Do we need this import?

2022-08-02 16:10 UTC, yangli2014 commented on platform/core/monitor/src/main/java/org/opennms/horizon/core/monitor/DeviceMonitorManager.java
> +    private final Map<String, Long> snmpinitialUpTime = new ConcurrentHashMap<>();
```suggestion
    private final Map<String, Long> snmpInitialUpTime = new ConcurrentHashMap<>();
```

2022-08-02 16:12 UTC, yangli2014 commented on shared-lib/dto-model/src/main/java/org/opennms/horizon/shared/dto/device/DeviceDTO.java
> +  private String managementIp;
As we discussed, we will add the IpIInterfaceDTO in getting DeviceDTO in another story.

2022-08-02 17:12 UTC, yangli2014 reviewed
Nice Job. There is an external-it test failure. 
And I got an exception in the scaffold terminal, I am not sure if it is related to this PR 
```
java.util.concurrent.CompletionException: org.opennms.horizon.ipc.rpc.api.RemoteExecutionException: java.util.concurrent.CompletionException: org.opennms.netmgt.snmp.SnmpException: org.opennms.netmgt.snmp.SnmpAgentTimeoutException: Timeout retrieving response for 127.0.0.1.
[horizon-stream-core]  at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
[horizon-stream-core]  at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
[horizon-stream-core]  at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
[horizon-stream-core]  at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
[horizon-stream-core]  at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
[horizon-stream-core]  at org.opennms.netmgt.snmp.snmp4j.Snmp4JStrategy$2.onResponse(Snmp4JStrategy.java:347)
[horizon-stream-core]  at org.snmp4j.Snmp$PendingRequest.run(Snmp.java:1878)
[horizon-stream-core]  at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[horizon-stream-core]  at java.base/java.util.TimerThread.run(Timer.java:506)
[horizon-stream-core] Caused by: org.opennms.netmgt.snmp.SnmpException: org.opennms.netmgt.snmp.SnmpAgentTimeoutException: Timeout retrieving response for 127.0.0.1.
[horizon-stream-core]  ... 4 more
[horizon-stream-core] Caused by: org.opennms.netmgt.snmp.SnmpAgentTimeoutException: Timeout retrieving response for 127.0.0.1.
[horizon-stream-core]  at org.opennms.netmgt.snmp.snmp4j.Snmp4JStrategy.processResponse(Snmp4JStrategy.java:420)
[horizon-stream-core]  at org.opennms.netmgt.snmp.snmp4j.Snmp4JStrategy$2.onResponse(Snmp4JStrategy.java:345)
```

2022-08-02 17:16 UTC, cgorantla commented
> Nice Job. There is an external-it test failure. And I got an exception in the scaffold terminal, I am not sure if it is related to this PR
> 
> ```
> java.util.concurrent.CompletionException: org.opennms.horizon.ipc.rpc.api.RemoteExecutionException: java.util.concurrent.CompletionException: org.opennms.netmgt.snmp.SnmpException: org.opennms.netmgt.snmp.SnmpAgentTimeoutException: Timeout retrieving response for 127.0.0.1.
> [horizon-stream-core]  at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
> [horizon-stream-core]  at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
> [horizon-stream-core]  at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
> [horizon-stream-core]  at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
> [horizon-stream-core]  at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
> [horizon-stream-core]  at org.opennms.netmgt.snmp.snmp4j.Snmp4JStrategy$2.onResponse(Snmp4JStrategy.java:347)
> [horizon-stream-core]  at org.snmp4j.Snmp$PendingRequest.run(Snmp.java:1878)
> [horizon-stream-core]  at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
> [horizon-stream-core]  at java.base/java.util.TimerThread.run(Timer.java:506)
> [horizon-stream-core] Caused by: org.opennms.netmgt.snmp.SnmpException: org.opennms.netmgt.snmp.SnmpAgentTimeoutException: Timeout retrieving response for 127.0.0.1.
> [horizon-stream-core]  ... 4 more
> [horizon-stream-core] Caused by: org.opennms.netmgt.snmp.SnmpAgentTimeoutException: Timeout retrieving response for 127.0.0.1.
> [horizon-stream-core]  at org.opennms.netmgt.snmp.snmp4j.Snmp4JStrategy.processResponse(Snmp4JStrategy.java:420)
> [horizon-stream-core]  at org.opennms.netmgt.snmp.snmp4j.Snmp4JStrategy$2.onResponse(Snmp4JStrategy.java:345)
> ```

yeah, this is related. It is logging SNMP Monitor error for `127.0.0.1`.  
On CI/CD, looks like it is related to Minion health check failure, not sure why it is coming now.

2022-08-08 21:49 UTC, geraldhumphries requested changes

2022-08-09 16:16 UTC, cgorantla commented on platform/core/monitor/src/main/java/org/opennms/horizon/core/monitor/DeviceMonitorManager.java
> +    public void setLocationAwarePingClient(LocationAwarePingClient locationAwarePingClient) {
@geraldhumphries  I wanted to avoid too many constructor args.  Those parameters that are needed in `init` are added in constructor and rest of them are added as properties.

2022-08-09 19:48 UTC, geraldhumphries commented on platform/core/monitor/src/main/java/org/opennms/horizon/core/monitor/DeviceMonitorManager.java
> +    public void setLocationAwarePingClient(LocationAwarePingClient locationAwarePingClient) {
Why avoid too many constructor args?

It is painful to work with too many constructor args, but that's a good thing. "Too many constructor args" means "too many dependencies", and beans with less dependencies are generally easier it is to maintain and test. It makes it way easier for developers to find candidates for refactor and it's actually one of the big reasons to use constructor injection.

IMO, regardless of what style of dependency injection is used, mixing different types should be avoided except in specific circumstances, like when we need to change deps on existing beans. Do we need to do that? I also noticed that all the dependencies that are method-injected are marked as `availability="optional"` in the blueprint. Is that related?

2022-08-09 21:04 UTC, cgorantla commented on platform/core/monitor/src/main/java/org/opennms/horizon/core/monitor/DeviceMonitorManager.java
> +    public void setLocationAwarePingClient(LocationAwarePingClient locationAwarePingClient) {
Moved to constructor.  Removed `availability="optional"`

2022-08-09 21:11 UTC, geraldhumphries approved these changes

2022-08-09 21:24 UTC, merged