HS-201: Call PagerDuty on alarm create
OpenNMS/horizon-stream pull request #252
Opened 2022-08-24 10:46 UTC by james8hut

## Description
Call PagerDuty on alarm create

## Jira link(s)
- https://issues.opennms.org/browse/HS-201

## Flagged for review
Should AlarmSeverity class move into the shared-lib? There are also classes called Severity and OnmsSeverity which are identical as far as I can see.

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.

2022-08-29 17:34 UTC, geraldhumphries requested changes

2022-08-29 17:34 UTC, geraldhumphries commented on notifications/src/main/java/org/opennms/horizon/notifications/api/dto/AlarmSeverity.java
> +    private String m_color;
We should avoid introducing this style of Hungarian notation into the notification codebase. I know this was probably a copy paste from Classic, but it's a good idea to refactor it.

2022-08-29 17:34 UTC, geraldhumphries commented on notifications/src/main/java/org/opennms/horizon/notifications/api/dto/AlarmSeverity.java
> +    private AlarmSeverity(final int id, final String label, final String color) {
I think the current preference for new code in Classic is to avoid the final keyword in method args. We should probably follow that as well.

2022-08-30 14:27 UTC, james8hut commented on notifications/src/main/java/org/opennms/horizon/notifications/api/PagerDutyAPIImpl.java
> +        }
Pro:
Once a field is marked as Optional, developer really can’t forget to handle the null case.

Yet, my personal opinion is that I don’t like it.

Con:
Code feels more complicated to look at. (Maybe with familiarity that feeling would reduce.) It also feels that the focus of the logic has shifted from the contents of the string, and what that means from a business perspective, to the fact that the string can be Null, and now the most important is handling the potential for Null.

I think it’s the wrapping that I don’t like. Feels like one extra thing to store in your head while trying to read and understand the code.

I’m aware that my dislike of this, is down to feeling rather than actual science or anything like that.

My feeling is that an attribute is a better feeling for how to describe nullable data.

e.g
@Nullable
String managedObjectType

I’m not sure that actually provides much value though.

My own thoughts are that if a String is null, and (a) it shouldn’t be, or (b) we’ve forgotten to do a check, then it’s ok to blow up with a NullPointerException as quickly as possible, so that we can fix the bug.

I should also point out I’m happy to use Optional if that’s what is decided is best across the entire project.

2022-08-30 14:27 UTC, james8hut commented on notifications/src/main/java/org/opennms/horizon/notifications/api/PagerDutyAPIImpl.java
> +            event.setEvent_action("trigger");
done, and done

2022-08-30 14:27 UTC, james8hut commented on notifications/src/main/java/org/opennms/horizon/notifications/api/PagerDutyAPIImpl.java
>          event.setClient_url("http://opennms.com");
will move

2022-08-30 14:27 UTC, james8hut commented on notifications/src/main/java/org/opennms/horizon/notifications/api/dto/AlarmSeverity.java
> +    private String m_color;
done

2022-08-30 14:34 UTC, james8hut commented on notifications/src/main/java/org/opennms/horizon/notifications/api/dto/AlarmSeverity.java
> +    private AlarmSeverity(final int id, final String label, final String color) {
done. I must admit that I very rarely use the final keyword for anything other than for String constants defined in a ConstantsClass or something like that.
Out of curiosity, do you know why final is frowned upon? Is it simply as code noise?

2022-08-30 14:36 UTC, james8hut commented on notifications/src/main/java/org/opennms/horizon/notifications/api/PagerDutyAPIImpl.java
> +        }
Having read up on people not liking final (see below), I think Optional hits the same flag for me, and feels like code noise.

2022-08-30 18:47 UTC, geraldhumphries commented on notifications/src/main/java/org/opennms/horizon/notifications/api/dto/AlarmSeverity.java
> +    private AlarmSeverity(final int id, final String label, final String color) {
Honestly, for OpenNMS, not sure. I've never used it myself aside from constants and injected dependencies.

2022-08-30 18:59 UTC, geraldhumphries requested changes

2022-08-30 18:59 UTC, geraldhumphries commented on notifications/src/main/java/org/opennms/horizon/notifications/api/dto/PagerDutyEventDTO.java
> +    String eventAction;
We should be able to use the `PagerDutyEventAction` enum here instead of a String. Adding `@JsonValue` to the `PagerDutyEventAction.getVal()` method should work for deserialization. 

Does this also need to be serialized, e.g. do we need to handle responses from PagerDuty that contain `PagerDutyEventAction`?

2022-08-30 18:59 UTC, geraldhumphries commented on notifications/src/main/java/org/opennms/horizon/notifications/api/PagerDutyAPIImpl.java
> +        payload.setSeverity(PagerDutySeverity.fromAlarmSeverity(alarmSeverity).toString());
Similar to `PagerDutyEventDTO`, can we use the severity enum in `PagerDutyPayloadDTO` directly?

2022-08-31 10:57 UTC, james8hut commented on notifications/src/main/java/org/opennms/horizon/notifications/api/dto/PagerDutyEventDTO.java
> +    String eventAction;
Currently only sending things one way to PagerDuty. Have implemented in line with the classic plugin.

2022-08-31 10:58 UTC, james8hut commented on notifications/src/main/java/org/opennms/horizon/notifications/api/PagerDutyAPIImpl.java
> +        payload.setSeverity(PagerDutySeverity.fromAlarmSeverity(alarmSeverity).toString());
Have implemented in line with the classic plugin.

2022-08-31 15:48 UTC, james8hut commented on notifications/src/main/java/org/opennms/horizon/notifications/api/dto/PagerDutyEventDTO.java
> +    String eventAction;
re-done using JsonValue

2022-08-31 15:48 UTC, james8hut commented on notifications/src/main/java/org/opennms/horizon/notifications/api/PagerDutyAPIImpl.java
> +        payload.setSeverity(PagerDutySeverity.fromAlarmSeverity(alarmSeverity).toString());
re-done using JsonValue

2022-08-31 18:01 UTC, geraldhumphries approved these changes

2022-09-01 07:32 UTC, merged