Minion gateway sends TaskResults to kafka, and core consumes + update…
OpenNMS/horizon-stream pull request #263
Opened 2022-08-30 19:28 UTC by artnaseef

…s metrics.  Note IP address and Location are currently missing for ICMP results.

## Description

## Jira link(s)
- https://issues.opennms.org/browse/HS-xx

## Flagged for review

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.

2022-08-30 19:37 UTC, mfrazier63 approved these changes
LGTM

2022-08-30 19:42 UTC, geraldhumphries requested changes
One small change, otherwise looks good!

2022-08-30 19:42 UTC, geraldhumphries commented on dev/kubernetes.kafka.yaml
> +              value: "kafka:9092"
Can you also add this to the deployment in `charts/opennms/templates/opennms`?

2022-08-31 23:19 UTC, artnaseef commented on dev/kubernetes.kafka.yaml
> +              value: "kafka:9092"
Looking at that, it appears we have some basic work to do to get minion-gateway in there.  I'm going to hold off because I'm confident that if I throw something in there, it'll be a mess at best.

2022-08-31 23:19 UTC, merged