HS-352: BFF non-block http request to backend service
OpenNMS/horizon-stream pull request #271
Opened 2022-09-02 19:46 UTC by yangli2014

## Description

## Jira link(s)
- https://issues.opennms.org/browse/HS-352

## Flagged for review

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.

2022-09-06 16:00 UTC, geraldhumphries requested changes

2022-09-06 16:00 UTC, geraldhumphries commented on rest-server/src/main/java/org/opennms/horizon/server/service/MinionService.java
> +    public MinionService(PlatformGateway gateway, CacheManager cacheManager) {
Extra constructor arg

2022-09-06 16:00 UTC, geraldhumphries commented on rest-server/src/main/resources/application.yml
> +      spec: maximumSize=10000,expireAfterWrite=120s
Is this config setting used any more?

2022-09-06 16:00 UTC, geraldhumphries commented on rest-server/src/main/java/org/opennms/horizon/server/service/PrometheusTSDBServiceImpl.java
> +    public Mono<TimeSeriesQueryResult> getMetric(String name, Map<String, String> labels) {
Are these Monos unboxed by the GQL libs? We don't need to do it ourselves?

2022-09-06 18:47 UTC, yangli2014 commented on rest-server/src/main/resources/application.yml
> +      spec: maximumSize=10000,expireAfterWrite=120s
It will initialize the spring CacheManager but we disabled the cache in the service layer.

2022-09-06 18:48 UTC, yangli2014 commented on rest-server/src/main/java/org/opennms/horizon/server/service/PrometheusTSDBServiceImpl.java
> +    public Mono<TimeSeriesQueryResult> getMetric(String name, Map<String, String> labels) {
Correct, it is unboxed by the GQL Spring boot lib

2022-09-06 19:25 UTC, geraldhumphries commented on rest-server/src/main/resources/application.yml
> +      spec: maximumSize=10000,expireAfterWrite=120s
Okay, is it still necessary to initialize CacheManager? Are we using it anywhere currently? If not, maybe we should remove this?

2022-09-07 17:03 UTC, cgorantla approved these changes
LGTM!

2022-09-07 18:55 UTC, geraldhumphries approved these changes

2022-09-07 20:13 UTC, merged