HS-358: Use Liquibase for notications database
OpenNMS/horizon-stream pull request #274
Opened 2022-09-06 13:12 UTC by james8hut

## Description
Jesse suggested using Liquibase for the notification database

## Jira link(s)
- https://issues.opennms.org/browse/HS-358

## Flagged for review
Should I refactor the Hungarian notation out of Migrator and MigratorAdminInitialize while I'm in here

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.

2022-09-06 13:46 UTC, cgorantla requested changes
I feel like we should separate notification data source implementation out of existing DB migration.   That would make it easy to maintain and cleaner.

2022-09-06 13:46 UTC, cgorantla commented on platform/db/schema-liquibase/src/main/liquibase/hs-0.1.0/tables/pagerDutyConfig.xml
> +            INSERT INTO pager_duty_config (token, integrationkey) VALUES ('x', 'y');
what are these initial values supposed to be ?

2022-09-06 14:21 UTC, james8hut commented on platform/db/schema-liquibase/src/main/liquibase/hs-0.1.0/tables/pagerDutyConfig.xml
> +            INSERT INTO pager_duty_config (token, integrationkey) VALUES ('x', 'y');
So the config table just contains a single row containing token and integration_key for calling PagerDuty. User would be required to update these values (via UI) to enable PagerDuty to work. When they do so, the single row is updated with valid values. I'll update the 'x' and 'y' values to 'INVALID' as that makes more sense. If the user attempts to use Pager Duty before setting up the config table, then an exception is thrown from PagerDuty API with Invalid Routing key.

2022-09-06 14:34 UTC, cgorantla commented on platform/db/schema-liquibase/src/main/liquibase/hs-0.1.0/tables/pagerDutyConfig.xml
> +            INSERT INTO pager_duty_config (token, integrationkey) VALUES ('x', 'y');
Why inserting in the first place ?

2022-09-06 14:45 UTC, cgorantla commented on platform/db/schema-liquibase/src/main/liquibase/hs-0.1.0/tables/pagerDutyConfig.xml
> +            INSERT INTO pager_duty_config (token, integrationkey) VALUES ('x', 'y');
If we don't have sensible defaults, I prefer not to insert anything.

2022-09-06 16:05 UTC, james8hut commented on platform/db/schema-liquibase/src/main/liquibase/hs-0.1.0/tables/pagerDutyConfig.xml
> +            INSERT INTO pager_duty_config (token, integrationkey) VALUES ('x', 'y');
Have updated not to insert anything

2022-09-06 16:12 UTC, geraldhumphries commented on platform/db/schema-liquibase/src/main/liquibase/hs-0.1.0/tables/pagerDutyConfig.xml
> +            INSERT INTO pager_duty_config (token, integrationkey) VALUES ('x', 'y');
I agree with Chandra, this would probably end up being more difficult to maintain in the long run. It's a little trick we would always need to keep in our heads.

2022-09-06 20:33 UTC, geraldhumphries commented
You may be able to reduce a lot of boilerplate with the use of the SpringLiquibase bean. 

Here's an example of it in use: https://github.com/jhipster/jhipster-sample-app/blob/main/src/main/java/io/github/jhipster/sample/config/LiquibaseConfiguration.java#L32

associated SpringLiquibaseUtilClass: https://github.com/jhipster/jhipster-lite/blob/main/src/main/resources/generator/server/springboot/dbmigration/liquibase/main/SpringLiquibaseUtil.java.mustache

And finally, Spring Boot has a LiquibaseAutoConfiguration bean that we may be able to use, but I have no experience with it: https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration.java

2022-09-07 15:57 UTC, cgorantla commented
@james8hut Do you still need changes in platform/db/schema ?

2022-09-07 16:01 UTC, james8hut commented
> @james8hut Do you still need changes in platform/db/schema ?

@cgorantla In the process of rolling all platform changes back :-)

2022-09-07 16:50 UTC, geraldhumphries approved these changes

2022-09-07 16:54 UTC, cgorantla approved these changes
LGTM!

2022-09-07 16:54 UTC, cgorantla commented on notifications/pom.xml
> +            <artifactId>h2</artifactId>
Add scope test

2022-09-07 16:54 UTC, cgorantla commented on notifications/src/main/resources/application.yml
> +  datasource:
Is this DB already part of skaffold/operator pipeline ?
If not we should create another issue to tackle that.

2022-09-07 17:25 UTC, geraldhumphries commented on notifications/src/main/resources/application.yml
> +  datasource:
Yeah, it is, as part of the postgres-initial-sql scripts.

2022-09-07 17:26 UTC, geraldhumphries commented on notifications/pom.xml
> +            <artifactId>h2</artifactId>
```suggestion
            <artifactId>h2</artifactId>
            <scope>test</scope>
```

2022-09-08 07:13 UTC, merged