HS-465,HS-466,HS-467,HS-468: Create Initial Inventory Service
OpenNMS/horizon-stream pull request #377
Opened 2022-10-14 11:13 UTC by thomasbigger584

** WORK IN PROGRESS **

## Description
Combining multiple stories due to the need to test liquibase with postgres in k8s cluster.

Adding new Inventory Service, connecting to its own database in postgres and performing migration of the database (similar to notification service throughout).
Adding Skaffold / Helm / Operator / Github Actions code as its relevant for adding the new service.

Schema will be based off the diagram in the Jira Link.

## Jira link(s)
- https://issues.opennms.org/browse/HS-465
- https://issues.opennms.org/browse/HS-466
- https://issues.opennms.org/browse/HS-467
- https://issues.opennms.org/browse/HS-468

## Checklist
* [x] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [x] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [x] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.

2022-10-17 13:57 UTC, cgorantla reviewed
I have a lot of questions on inheriting the same tables as classic. Let'd discuss this more thoroughly in a call.

2022-10-17 13:57 UTC, cgorantla commented on inventory/pom.xml
> +        <groupId>org.springframework.boot</groupId>
we should use parent pom like here : https://github.com/OpenNMS/horizon-stream/blob/b6e451742e24498d39217e89981fbe91e30a0f4c/minion-gateway/pom.xml#L6

2022-10-17 13:57 UTC, cgorantla commented on inventory/pom.xml
> +        <dependency>
It would be good to not mix test and main dependencies.

2022-10-17 13:57 UTC, cgorantla commented on inventory/src/main/resources/db/changelog/hs-0.1.0/tables/node.xml
> +            <column name="dpname" type="varchar(12)"/>
probably don't need this

2022-10-17 13:57 UTC, cgorantla commented on inventory/src/main/resources/db/changelog/hs-0.1.0/tables/node.xml
> +            <column name="nodeid" type="integer">
type could be biginteger

2022-10-17 13:57 UTC, cgorantla commented on inventory/src/main/resources/db/changelog/hs-0.1.0/tables/node.xml
> +            <column name="nodeparentid" type="integer"/>
can remove this

2022-10-17 13:57 UTC, cgorantla commented on inventory/src/main/resources/db/changelog/hs-0.1.0/tables/node.xml
> +            <column name="nodetype" type="char(1)"/>
not sure we need this

2022-10-17 13:57 UTC, cgorantla commented on inventory/src/main/resources/db/changelog/hs-0.1.0/tables/node.xml
> +            <column name="nodesyscontact" type="varchar(256)"/>
Should we move this into different table ?

2022-10-17 13:57 UTC, cgorantla commented on inventory/src/main/resources/db/changelog/hs-0.1.0/tables/node.xml
> +            <column name="nodelabelsource" type="char(1)"/>
we shouldn't need this, even if we have shouldn't be based on flag I believe

2022-10-17 13:57 UTC, cgorantla commented on inventory/src/main/resources/db/changelog/hs-0.1.0/tables/node.xml
> +            <column name="lastcapsdpoll" type="TIMESTAMP WITH TIME ZONE"/>
It should be renamed, `lastscantime` ?

2022-10-20 09:18 UTC, james8hut approved these changes
Can we merge this as it currently stands? Then potentially have another PR to deal with adding extra tables.

2022-10-20 09:33 UTC, thomasbigger584 commented
> Can we merge this as it currently stands? Then potentially have another PR to deal with adding extra tables.

yes sure will get this ready for a merge, can look at liquibase schemas in another PR

2022-10-20 12:24 UTC, james8hut requested changes

2022-10-20 12:24 UTC, james8hut commented on charts/opennms/templates/opennms/inventory/inventory-deployment.yaml
> +      run: {{ .Values.OpenNMS.Inventory.ServiceName }}
Think this needs to change from run to app

2022-10-20 12:24 UTC, james8hut commented on charts/opennms/templates/opennms/inventory/inventory-deployment.yaml
> +        run: {{ .Values.OpenNMS.Inventory.ServiceName }}
Same here

2022-10-20 12:26 UTC, thomasbigger584 commented on charts/opennms/templates/opennms/inventory/inventory-deployment.yaml
> +      run: {{ .Values.OpenNMS.Inventory.ServiceName }}
done

2022-10-20 12:27 UTC, thomasbigger584 commented on charts/opennms/templates/opennms/inventory/inventory-deployment.yaml
> +        run: {{ .Values.OpenNMS.Inventory.ServiceName }}
done

2022-10-20 13:28 UTC, cgorantla commented on inventory/src/main/resources/db/changelog/hs-0.1.0/tables/node.xml
> +            <column name="id" type="BIGSERIAL" autoIncrement="true" />
Looks like BIGSERIAL is not desirable with JPA, we can stick with bigint and use sequence generator https://vladmihalcea.com/postgresql-serial-column-hibernate-identity/#:~:text=SERIAL%20or%20BIGSERIAL,-If%20you've&text=SERIAL%20is%20an%20auto%2Dincremented,upon%20inserting%20a%20new%20ROW.

2022-10-20 13:28 UTC, cgorantla commented on inventory/src/main/resources/db/changelog/hs-0.1.0/tables/node.xml
> +            <column name="tenant_id" type="BIGINT">
I think this would be String or UUID

2022-10-20 15:52 UTC, yangli2014 approved these changes

2022-10-21 09:09 UTC, thomasbigger584 commented
Fixed conflicts and removed the node liquibase schema, in favour of adding all schemas in the next PR.

2022-10-21 09:13 UTC, merged