HS-483 - testing runner
OpenNMS/horizon-stream pull request #379
Opened 2022-10-14 14:58 UTC by jaymberry

## Description

## Jira link(s)
- https://issues.opennms.org/browse/HS-xx

## Flagged for review

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.

2022-10-20 17:42 UTC, geraldhumphries requested changes

2022-10-20 17:42 UTC, geraldhumphries commented on .github/actions/external-it/action.yml
> +        #which operator-sdk
We can remove these.

2022-10-20 17:42 UTC, geraldhumphries commented on .github/actions/external-it/action.yml
> +        #./local-sample/run.sh cicd
Similar to above, we can remove commented-out lines.

2022-10-20 17:42 UTC, geraldhumphries commented on .github/actions/external-it/action.yml
> +        sleep 120
Doesn't `kind load` wait until the image is finished loading to exit? Do we need to sleep?

2022-10-20 17:42 UTC, geraldhumphries commented on .github/actions/external-it/action.yml
> +        kubectl -n local-instance patch deployments grafana                -p '{"spec": {"template": {"spec":{"containers":[{"name": "grafana",               "image":"opennms/horizon-stream-grafana:l
Shouldn't we do this in the CRD? The operator will overwrite these changes otherwise.

2022-10-20 17:42 UTC, geraldhumphries commented on install-local.sh
> +while [ -v $(kubectl get pods -n local-instance -l=app.kubernetes.io/component='controller-local-instance' -o jsonpath='{.items[*].status.containerStatuses[0].ready}')  ]; do
Is it possible to wait until the CRD instance is ready? The operator will mark it as ready when all its resources are ready.

2022-10-20 17:42 UTC, geraldhumphries commented on operator/scripts/deploy-horizon-stream.sh
> +while [ -v $(kubectl get pods -n local-instance -l=app.kubernetes.io/component='controller-local-instance' -o jsonpath='{.items[*].status.containerStatuses[0].ready}')  ]; do
Same as above regarding CRD instance state,

2022-10-20 17:42 UTC, geraldhumphries commented on .github/actions/external-it/action.yml
> +        kind delete clusters kind
Maybe move this to another "cleanup" step?

2022-10-20 17:46 UTC, jaymberry commented on .github/actions/external-it/action.yml
> +        sleep 120
Yes, but I am running them all at once in the background, so need to set a time limit before moving onto next step.

2022-10-20 17:46 UTC, jaymberry commented on .github/actions/external-it/action.yml
> +        kubectl -n local-instance patch deployments grafana                -p '{"spec": {"template": {"spec":{"containers":[{"name": "grafana",               "image":"opennms/horizon-stream-grafana:l
Right, ok, I can re-work this a little, good point.

2022-10-20 19:21 UTC, jaymberry commented on operator/scripts/deploy-horizon-stream.sh
> +while [ -v $(kubectl get pods -n local-instance -l=app.kubernetes.io/component='controller-local-instance' -o jsonpath='{.items[*].status.containerStatuses[0].ready}')  ]; do
This is the only way I could accurately wait until it is ready.

2022-10-20 19:47 UTC, jaymberry commented on .github/actions/external-it/action.yml
> +        #./local-sample/run.sh cicd
Removed

2022-10-20 19:47 UTC, jaymberry commented on .github/actions/external-it/action.yml
> +        kind delete clusters kind
Done

2022-10-20 19:53 UTC, geraldhumphries commented on operator/scripts/deploy-horizon-stream.sh
> +while [ -v $(kubectl get pods -n local-instance -l=app.kubernetes.io/component='controller-local-instance' -o jsonpath='{.items[*].status.containerStatuses[0].ready}')  ]; do
If you are using the operator then it should be doing that job for you, is there an issue with it? Note that "deployOnly: true" in the CRD will disable the operator waiting until deployments are ready, and it will mark the instance as ready right away.

2022-10-20 20:20 UTC, jaymberry commented on operator/scripts/deploy-horizon-stream.sh
> +while [ -v $(kubectl get pods -n local-instance -l=app.kubernetes.io/component='controller-local-instance' -o jsonpath='{.items[*].status.containerStatuses[0].ready}')  ]; do
No, it does not. It just starts the build and then gives the session back while it builds the local-instance env. We need to add additional steps to check.

2022-10-21 13:56 UTC, geraldhumphries approved these changes

2022-10-21 13:59 UTC, merged