HS-446: Handle traps listening
OpenNMS/horizon-stream pull request #387
Opened 2022-10-19 14:20 UTC by cgorantla

## Description
Add Traps Listener to Minion
Kafka Forwarder on Minion Gateway
Update Core to handle traps.
Config updates with Twin functionality is not completed in this PR.

## Jira link(s)
- https://issues.opennms.org/browse/HS-446

## Flagged for review

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.

2022-10-20 21:35 UTC, splatch requested changes
There are minor-ish things which could be addressed in order to keep improving consistency in minion code base. These are mostly an assumed conventions which are not written in stone. Feel free to ignore or question them if you feel they are not right.

I am not entirely clear about use of snmp4j in core, since I don't know what trap contents are, hence I'd welcome if you could drop a line about it.

2022-10-20 21:35 UTC, splatch commented on shared-lib/horizon-ipc/ipc-grpc/ipc-grpc-contract/src/main/proto/opennms/traps/traps.proto
> +message SnmpValue {
I think you have imported definition of `SnmpValue` from `snmp.proto` in line 7, so these are redundant. If protoc does complain then we probably have to look for proper package prefix or something to avoid dupliucation.

2022-10-21 16:40 UTC, cgorantla commented on minion/pom.xml
> +        <module>traps</module>
I still prefer not having minion appended but updated according to current convention!

2022-10-21 16:42 UTC, cgorantla commented on minion/traps/features/src/main/feature/feature.xml
> +    <repository>mvn:org.opennms.horizon.shared/snmp-api/${project.version}/xml/features</repository>
Updated! Traps module is dependent on `snmp-snmp4j` module not just api. We can move `snmp-snmp4j` feature into shared lib as a separate PR

2022-10-21 16:44 UTC, cgorantla commented
> I am not entirely clear about use of snmp4j in core, since I don't know what trap contents are, hence I'd welcome if you could drop a line about it.

Core is also dependent on snmp4j implementation for parsing the traps.  Traps Consumption is going to be separate module, we can look at Core integration more closely with that service.

2022-10-21 16:50 UTC, splatch approved these changes
LGTM

2022-10-25 20:29 UTC, merged