Feature/mmf/gateway json diff
OpenNMS/horizon-stream pull request #402
Opened 2022-10-24 18:58 UTC by mfrazier63

## Description
Enables JSON diffs in the minion gateway to minimize data sent down tot he minions. 
Switches over to zjsonpatch as well
Moved the marshalling code into shared for easier round trip testing

## Jira link(s)
- https://issues.opennms.org/browse/HS-xx

## Flagged for review

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.

2022-10-24 22:41 UTC, artnaseef approved these changes

2022-10-25 16:57 UTC, splatch requested changes
Direction looks promising, however unit test for subscriber is blind. Making it functional with some asserts will prove that it works with protobuf payload. Same thing applies to twin publisher.

2022-10-25 16:57 UTC, splatch commented on shared-lib/protobuf/src/main/java/org/opennms/horizon/shared/protobuf/marshalling/ProtoBufJsonDeserializer.java
> +@Data
I think `@Data` is not needed here

2022-10-25 16:57 UTC, splatch commented on shared-lib/protobuf/src/test/java/org/opennms/horizon/protobuf/marshalling/ProtoBufJsonSerializationTest.java
> +        simpleModule.addDeserializer(TaskSet.class, new ProtoBufJsonDeserializer<>(TaskSet.class));
Can you try this code with `protobuf.Message`? Maybe we will be able to avoid dynamic class binding?

2022-10-25 16:57 UTC, splatch commented on minion/minion-ipc/twin-common/src/test/java/org/opennms/horizon/minion/ipc/twin/common/SubscriptionTest.java
> +public class SubscriptionTest {
This test is currently incomplete.

2022-10-25 17:42 UTC, mfrazier63 commented on shared-lib/protobuf/src/test/java/org/opennms/horizon/protobuf/marshalling/ProtoBufJsonSerializationTest.java
> +        simpleModule.addDeserializer(TaskSet.class, new ProtoBufJsonDeserializer<>(TaskSet.class));
Already had, doesn't work.

2022-10-25 18:01 UTC, mfrazier63 commented on minion/minion-ipc/twin-common/src/test/java/org/opennms/horizon/minion/ipc/twin/common/SubscriptionTest.java
> +public class SubscriptionTest {
- [ ] make test functional

2022-10-25 18:01 UTC, mfrazier63 commented on shared-lib/protobuf/src/main/java/org/opennms/horizon/shared/protobuf/marshalling/ProtoBufJsonDeserializer.java
> +@Data
- [ ] switch to @RequiredArgsConstructor

2022-10-28 16:26 UTC, mfrazier63 commented
Commits rolled into upcoming PR from @artnaseef

2022-10-28 16:35 UTC, artnaseef commented
The commits here are now part of the minion docker-it PR, so closing this one.

2022-10-28 16:35 UTC, closed without merging