HS-514 Convert task result to metric in generic way
OpenNMS/horizon-stream pull request #407
Opened 2022-10-26 16:34 UTC by yangli2014

## Description

After the local environment is launched, add an SNMP device on the UI page and then verify ICMP_msec and SNMP_msec metrics data collected in the Prometheus server
## Jira link(s)
- https://issues.opennms.org/browse/HS-514

## Flagged for review

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.

2022-10-26 16:50 UTC, cgorantla requested changes

2022-10-26 16:50 UTC, cgorantla commented on metrics-processor/src/main/java/org/opennms/horizon/tsdata/TSDataProcessor.java
> +            .name(response.getMonitorType().name())
I think we want `response_time` as metric name and monitor type added as label.

2022-10-26 16:50 UTC, cgorantla commented on metrics-processor/src/main/java/org/opennms/horizon/tsdata/TSDataProcessor.java
> +            .name(response.getMonitorType().name())
Also as per prometheus metric naming convention, we can append `_msec` to the name.  I'm okay with omitting it.

2022-10-26 16:50 UTC, cgorantla commented on shared-lib/protobuf/src/main/proto/taskSet.proto
> +  map<string, string> extra_labels = 9;
I guess we can add when we need this. Don't see any use for it now!

2022-10-26 23:21 UTC, yangli2014 commented on metrics-processor/src/main/java/org/opennms/horizon/tsdata/TSDataProcessor.java
> +            .name(response.getMonitorType().name())
it automatically append the _ and unit at the end of the name

2022-10-27 01:04 UTC, yangli2014 commented on metrics-processor/src/main/java/org/opennms/horizon/tsdata/TSDataProcessor.java
> +            .name(response.getMonitorType().name())
I use SNMP_response_time_msec as the metrics name.

2022-10-27 05:33 UTC, j-white commented on metrics-processor/src/main/java/org/opennms/horizon/tsdata/TSDataProcessor.java
> +            .name(response.getMonitorType().name())
Agreed. I think it makes more sense to have the monitor as a label here, rather than prefixing the metric name.

2022-10-27 05:43 UTC, j-white commented on metrics-processor/src/main/java/org/opennms/horizon/tsdata/TSDataProcessor.java
> +                    .name(k)
Include a prefix here, such as "monitor_" so that these don't collide with other metrics. Similar to above, include the monitor as a label as well, so we can associate this back with the monitor.

2022-10-27 14:21 UTC, yangli2014 commented
@j-white @cgorantla Let me know if the following change is good enough
![Screenshot 2022-10-27 at 10 19 41 AM](https://user-images.githubusercontent.com/9009178/198312013-4da37a79-ca69-4e29-9a3d-94b17874e4d8.png)

2022-10-27 14:26 UTC, cgorantla commented on metrics-processor/src/main/java/org/opennms/horizon/tsdata/TSDataProcessor.java
> +                Gauge extGauge = getGaugeFromName(METRICS_NAME_PREFIX_MONITOR + k, false);
I think we want `monitor_` prefix only for extra metrics that are coming from the response not for the response_time.

Also as you pointed before, we don't need to add unit in the name.

2022-10-27 14:57 UTC, yangli2014 commented on metrics-processor/src/main/java/org/opennms/horizon/tsdata/TSDataProcessor.java
> +                Gauge extGauge = getGaugeFromName(METRICS_NAME_PREFIX_MONITOR + k, false);
So the type label will be changed to monitor_type="ICMP"?

2022-10-27 15:01 UTC, cgorantla commented on metrics-processor/src/main/java/org/opennms/horizon/tsdata/TSDataProcessor.java
> +                Gauge extGauge = getGaugeFromName(METRICS_NAME_PREFIX_MONITOR + k, false);
monitor="ICMP" should be good enough!

2022-10-27 15:30 UTC, yangli2014 commented on metrics-processor/src/main/java/org/opennms/horizon/tsdata/TSDataProcessor.java
> +                Gauge extGauge = getGaugeFromName(METRICS_NAME_PREFIX_MONITOR + k, false);
updated. thanks

2022-10-27 15:59 UTC, cgorantla commented on metrics-processor/src/main/java/org/opennms/horizon/tsdata/TSDataProcessor.java
> +            if(withDesc) {
nit: looks like this file is not formatted!

2022-10-27 16:12 UTC, cgorantla approved these changes
LGTM!

2022-10-27 18:14 UTC, merged