HS-471 gRPC service in inventory service
OpenNMS/horizon-stream pull request #421
Opened 2022-11-04 13:48 UTC by yangli2014

## Description

After inventory starts, make sure the log showing gRPC server started with port 6565 
## Jira link(s)
- https://issues.opennms.org/browse/HS-471

## Flagged for review

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.

2022-11-04 14:07 UTC, james8hut commented on inventory/src/main/java/org/opennms/horizon/inventory/model/MonitoringLocation.java
> +import javax.persistence.Id;
This change was made in my latest PR. So maybe a merge conflict as I think that should be in develop already.
Maybe you want to get latest develop branch?

2022-11-04 14:12 UTC, james8hut commented on shared-lib/inventory/src/main/proto/opennms/inventory.proto
> +service LocationService {
Question about the rename. Should all tables appear in the same proto file? I've been adding new tables in different proto files.

2022-11-04 14:14 UTC, james8hut requested changes

2022-11-04 14:14 UTC, james8hut commented on shared-lib/inventory/src/main/proto/opennms/inventory.proto
> +  rpc UpdateLocation(MonitoringLocationDTO) returns (MonitoringLocationDTO) {};
should UpdateLocation be updateLocation in line with other naming conventions?

2022-11-04 14:18 UTC, james8hut commented on inventory/src/main/java/org/opennms/horizon/inventory/service/LocationGrpcService.java
> +            responseObserver.onNext(mapper.modelToDTO(locationRepo.save(mapper.dtoToModel(request))));
Query on this. If the id exists, should we throw an error? Just for my own knowledge, does the rest of the application do an update in this scenario or throw an error?

2022-11-04 14:58 UTC, cgorantla requested changes

2022-11-04 14:58 UTC, cgorantla commented on shared-lib/inventory/src/main/proto/opennms/inventory.proto
> +service LocationService {
We don't need to create all CRUD operations, currently BFF only need all locations and locations by location name, that's all we need to expose.

2022-11-04 14:58 UTC, cgorantla commented on shared-lib/inventory/src/main/proto/opennms/inventory.proto
> +  rpc listLocations(google.protobuf.Empty) returns (stream MonitoringLocationDTO) {};
stream in `grpc` is different, it's continuous flow of data.

2022-11-04 14:58 UTC, cgorantla commented on inventory/pom.xml
> +        <dependency>
IMO, we shouldn't bring unofficial spring boot starters.
We can re-use config like `GrpcIpcServerConfig` and `GrpcIpcUtils` for configuring server.

2022-11-04 15:36 UTC, yangli2014 commented on inventory/src/main/java/org/opennms/horizon/inventory/model/MonitoringLocation.java
> +import javax.persistence.Id;
sure

2022-11-04 15:38 UTC, yangli2014 commented on shared-lib/inventory/src/main/proto/opennms/inventory.proto
> +service LocationService {
I just discussed this with Chandra, we keep two files. One for nodes and another one for monitoring.

2022-11-04 15:38 UTC, yangli2014 commented on shared-lib/inventory/src/main/proto/opennms/inventory.proto
> +  rpc UpdateLocation(MonitoringLocationDTO) returns (MonitoringLocationDTO) {};
good catch

2022-11-04 15:41 UTC, yangli2014 commented on inventory/src/main/java/org/opennms/horizon/inventory/service/LocationGrpcService.java
> +            responseObserver.onNext(mapper.modelToDTO(locationRepo.save(mapper.dtoToModel(request))));
In classic, the location name is the primary key if I remember correctly. Also, I am unsure if we have a use case to change the location name.

2022-11-07 12:50 UTC, thomasbigger584 commented on inventory/src/main/java/org/opennms/horizon/inventory/grpc/GrpcConfig.java
> +    public GrpcConfig(MonitoringLocationRepository locationRepo) {
for consistency we can use `@RequiredArgsConstructor` instead of this constructor. This will auto generate with Lombok the constructor if the fields are final, thus giving dependency injection with less code. Same with other classes in the PR.

2022-11-07 12:50 UTC, thomasbigger584 commented on inventory/src/main/java/org/opennms/horizon/inventory/service/InventoryGrpcService.java
> +    private final MonitoringLocationMapper mapper = Mappers.getMapper(MonitoringLocationMapper.class);
this can be constructor injected as its a spring bean, instead of statically referencing it. Same with other occurences in the PR.

2022-11-07 12:50 UTC, thomasbigger584 commented on inventory/src/main/java/org/opennms/horizon/inventory/repository/MonitoringLocationRepository.java
> +    MonitoringLocation findByLocation(String location);
If this returns `Optional<MonitoringLocation>` then we can have cleaner null checking in the service with the `.isPresent()` method

2022-11-07 13:16 UTC, james8hut commented on inventory/src/main/java/org/opennms/horizon/inventory/service/InventoryGrpcService.java
> +    private final MonitoringLocationMapper mapper = Mappers.getMapper(MonitoringLocationMapper.class);
If you merge with develop, you'll see the Mapper has changed slightly. @Mapper(componentModel = "spring"), and you'll also see that Mappers.getMapper is no longer used elsewhere.

2022-11-07 14:46 UTC, cgorantla commented on inventory/src/main/java/org/opennms/horizon/inventory/grpc/GrpcConfig.java
> +    public GrpcConfig(MonitoringLocationRepository locationRepo) {
My 2 cents: I'm not a fan of lombok. When we get to Java 17, we don't need `lombok` in many places.  Records are much better.

2022-11-07 14:49 UTC, cgorantla commented on inventory/src/main/resources/application.yml
> +    max.message.size: 104857600
`max.message.size` may not be needed here. It was needed for IPC but no need for it on API.

2022-11-07 14:51 UTC, cgorantla commented on shared-lib/inventory/src/main/proto/monitoring.proto
> +  rpc listLocations(google.protobuf.Empty) returns (stream MonitoringLocationDTO) {};
we need a list of MonitoringLocationDTO here not a Stream.

2022-11-07 15:01 UTC, cgorantla commented on inventory/src/main/java/org/opennms/horizon/inventory/grpc/GrpcConfig.java
> +    public GrpcConfig(MonitoringLocationRepository locationRepo) {
Once we get rid of Core, we can move to Java 17. So in a month or two.

2022-11-07 15:29 UTC, yangli2014 commented on shared-lib/inventory/src/main/proto/monitoring.proto
> +  rpc listLocations(google.protobuf.Empty) returns (stream MonitoringLocationDTO) {};
If the server uses the stream, the client still can get a list. I will keep it for now. If there is any issue when ingrate with BFF, we can change it.

2022-11-07 21:45 UTC, cgorantla commented on shared-lib/inventory/src/main/proto/monitoring.proto
> +  rpc listLocations(google.protobuf.Empty) returns (stream MonitoringLocationDTO) {};
As we chatted, this needs to be list but I'm okay to change when you update the client.

2022-11-07 21:48 UTC, cgorantla commented on inventory/src/test/java/org/opennms/horizon/inventory/grpc/GrpcIntegrationTest.java
> +        Iterator<MonitoringLocationDTO> result = serviceStub.listLocations(Empty.newBuilder().build());
This test may be unstable depending on the timing whether Iterator gets 1 or 2 elements, it's better to update API to return list

2022-11-08 14:33 UTC, cgorantla approved these changes

2022-11-08 15:20 UTC, merged