Adjust keycloak helm chart to avoid troubles with routing.
OpenNMS/horizon-stream pull request #453
Opened 2022-11-10 21:58 UTC by splatch

I did verify Keycloak configuration and 19.0.3 (.2 probably too) have a bug related to detection of https from actual configuration. There are few options which are available the most stable seem to be HOSTNAME_URL which allows to pass https, host and port all together. The https detection with hostname alone doesn't work and needs KC_HOSTNAME_STRICT_HTTPS to be set to false, which is undocumented feature.

Shipping it for now, as there is a pending issue in Keycloak itself: keycloak/keycloak#15287, which awaits resolution in release later than we use.

## Description

## Jira link(s)
- https://issues.opennms.org/browse/HS-xx

## Flagged for review

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.

2022-11-10 22:21 UTC, geraldhumphries requested changes

2022-11-10 22:21 UTC, geraldhumphries commented on charts/opennms/values.yaml
> +  HostnameAdminUrl: http://localhost:8123/auth
These values are specific to our local dev setup, and should not be in the chart's defaults. Instead, add them in the `tilt-helm-values.yaml` at the root of the repo.

2022-11-10 22:22 UTC, geraldhumphries commented on charts/opennms/templates/keycloak/keycloak-deployment.yaml
> +            {{- if .Values.Keycloak.AdminUsername }}
What is the impact if AdminUsername/AdminPassword are not set? Are there cases where we do not want them?

2022-11-10 22:23 UTC, splatch commented on charts/opennms/values.yaml
> +  HostnameAdminUrl: http://localhost:8123/auth
Roger!

2022-11-10 22:39 UTC, geraldhumphries commented on charts/opennms/templates/keycloak/keycloak-deployment.yaml
> +            - name: KC_HOSTNAME_PATH
I know that KC_HOSTNAME_URL will override both KC_HOSTNAME and KC_HOSTNAME_PORT, and I was under the impression that KC_HOSTNAME_PATH works the same way - the path in KC_HOSTNAME_URL (e.g. "auth" from `http://localhost:8123/auth`) will take precedence. Since KC_HOSTNAME_URL is always set, can you verify if KC_HOSTNAME_PATH is actually necessary?

I also remember there being a big difference between how KC_HTTP_RELATIVE_PATH and KC_HOSTNAME_PATH behave, and I had picked KC_HTTP_RELATIVE_PATH for a reason. I think it was related to either the admin console or Grafana's SSO. Can you check that the following are all working with these changes through Tilt?

1. Core service's connection to Keycloak, when it checks roles (Keycloak's backchannel communication)
2. Access to Keycloak's admin console at `http://localhost:8123/auth` without incorrect urls for CSS/JS/form submissions (Keycloak's "adminUrl" related settings)
3. Grafana's SSO at `http://localhost:8123/grafana` (Keycloak's frontend URL settings, I believe). This may actually be broken on develop, it is redirecting to port 80 when I tried it!

2022-11-10 22:40 UTC, splatch commented on charts/opennms/templates/keycloak/keycloak-deployment.yaml
> +            {{- if .Values.Keycloak.AdminUsername }}
This is a workaround for cases when database has been populated. Historically it was possible to add admin account by 1) environment variables 2) a magical `keycloak-add-user.json` file 3) realm import, although I am not certain if its possible for master realm. It might have changed a bit with quarkus distribution, but its still found in 19.0.x code. Alternative path could be ie. sidecar with json file.

2022-11-10 22:49 UTC, splatch commented on charts/opennms/templates/keycloak/keycloak-deployment.yaml
> +            - name: KC_HOSTNAME_PATH
My case was impossibility to login into admin console and ui due to port/https clash. Looking at code I think relative path might be still used to link a welcome page to admin page. You're right that we do not need `HOSTNAME_PATH` because it is detectable from entire URL. Its recommended use is only we rewrite ie. `/login` on ingress to `/` on keycloak. I'll remove it.

Going to check grafana and see if it survives.

2022-11-10 23:05 UTC, splatch commented on charts/opennms/templates/keycloak/keycloak-deployment.yaml
> +            - name: KC_HOSTNAME_PATH
Grafana seems to be giving wrong redirect_uri to keycloak. Grafana declares http://localhost/grafana as intended redirect which is wrong. So it is not catching 8123 thing properly as well.

2022-11-10 23:53 UTC, geraldhumphries commented on charts/opennms/templates/keycloak/keycloak-deployment.yaml
> +            - name: KC_HOSTNAME_PATH
Grafana's redirect_uri comes from the `rool_url` option under `[server]`. It is missing the port number. This config worked during local dev.

<img width="876" alt="image" src="https://user-images.githubusercontent.com/5278953/201230145-9c5606e6-614b-4c56-87f5-d20822e6e0dc.png">

2022-11-15 23:52 UTC, splatch commented
Looking at direction in which I began moving I think this PR needs to be closed. The Keycloak URI handling is far from being perfect and issues are crossing several aspects. The ingress blind of port forwards in tilt and Keycloak making its own logic to navigate all this.
I found out that we can get Grafana redirects working locally if we set ` domain = {{ .Values.Host }}:{{ .Values.Ingress.HttpPort}}`, however this forces http which is fine for development but not going to fly with production deployments.

2022-11-15 23:52 UTC, closed without merging