HS-432: Traps as events
OpenNMS/horizon-stream pull request #465
Opened 2022-11-17 17:03 UTC by cgorantla

## Description
Consume traps -> convert to events based on event conf.
Consume events -> persist into DB.

## Jira link(s)
- https://issues.opennms.org/browse/HS-432

## Flagged for review
1st commit is (Add Event conf) mostly event config and it's related beans ( Can be skipped)
Review 2nd commit.

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.

2022-11-17 17:06 UTC, cgorantla commented
Need some End to End tests but this is what I get by sending a Trap like below

`kubectl run --rm -it --image polinux/snmpd --restart=Never --command -- snmp-trap-pod /usr/bin/snmptrap -v 2c -c public  10.244.0.75:1162 '' 1.3.6.1.4.1.8072.2.3.0.1 1.3.6.1.4.1.8072.2.3.2.1 i 123456`

```
2022-11-17 16:58:11.055  INFO 1 --- [ntainer#1-0-C-1] o.o.h.events.consumer.EventsConsumer     : Received event from kafka event {
  uei: "uei.opennms.org/generic/traps/EnterpriseDefault"
  location: "Default"
  ip_address: "127.0.0.1"
  produced_time: 1668704290913
  event_info {
    snmp {
      id: ".1.3.6.1.4.1.8072.2.3"
      version: "v2"
      specific: 1
      generic: 6
      community: "public"
      trap_oid: ".1.3.6.1.4.1.8072.2.3.0.1"
    }
  }
}

2022-11-17 16:58:11.193  INFO 1 --- [ntainer#1-0-C-1] o.o.h.events.consumer.EventsConsumer     : Persisted 1 events in DB
```

2022-11-17 18:20 UTC, geraldhumphries requested changes

2022-11-17 18:20 UTC, geraldhumphries commented on events/traps/src/main/java/org/opennms/horizon/events/traps/TrapsConsumer.java
> +                trapdInstrumentation.incErrorCount();
This is somewhere that using the observer pattern might make more sense. I guess `trapdInstrumentation` is not used right now?

2022-11-17 18:29 UTC, cgorantla commented on events/traps/src/main/resources/spring-beans-context.xml
> +</beans>
This SnmpHelper class is coming from `shared-lib`. Don't want to add spring dependencies there.

2022-11-17 18:38 UTC, geraldhumphries commented on events/main/src/main/resources/application.yml
> +  events-topic: "events-proto"
Makes sense to me!

2022-11-18 11:39 UTC, james8hut commented on events/consumer/src/main/java/org/opennms/horizon/events/consumer/EventsConsumer.java
> +    @Autowired
Elsewhere in the code, we've been defining the likes of eventRepository as private final, and using Lombok's RequiredArgsConstructor. Possibly an idea to use that?

2022-11-18 11:51 UTC, james8hut commented on events/consumer/src/main/java/org/opennms/horizon/events/consumer/EventsConsumer.java
> +                LOG.warn("TenantId is empty, dropping events {}", eventLog);
General question on this for my own understanding. Under what scenarios can tenant id be null? If it should never be null (as I suspect), does this imply that there is a bug elsewhere in the code? If it is a bug, is logging a warning enough? (I get that we may still want to swallow this at this point to allow processing to continue, but is there anything else that can be done to report back to us that things are going wrong?) Maybe this is more of a question for the group?

2022-11-18 12:02 UTC, james8hut commented on events/traps/src/main/java/org/opennms/horizon/events/traps/EventCreator.java
> +        // TODO: Query inventory service for node id
Whilst this is obviously not done yet, do we require tenantId for this method? Can 2 different tenants have the same location and trapAddress.

2022-11-18 17:51 UTC, cgorantla commented on events/consumer/pom.xml
> +        <version>0.1.0-SNAPSHOT</version>
This is not permitted in parent context

2022-11-18 17:51 UTC, cgorantla commented on events/consumer/pom.xml
> +                <artifactId>spring-boot-dependencies</artifactId>
As discussed, @yangli2014 is already on it.

2022-11-18 17:51 UTC, cgorantla commented on events/consumer/src/main/java/org/opennms/horizon/events/consumer/EventsConsumer.java
> +    private Optional<String> getTenantId(Map<String, Object> headers) {
For Kafka, we are always getting it from headers, this is just convenient for header parsing, not much logic here to move it to separate class.  Once we get Tenant Id from Minion gateway, I will update this.

2022-11-18 17:51 UTC, cgorantla commented on events/traps/src/main/java/org/opennms/horizon/events/traps/TrapsConsumer.java
> +                trapdInstrumentation.incErrorCount();
Removed Instrumentation for now, added a TODO

2022-11-18 17:51 UTC, cgorantla commented on events/consumer/src/main/java/org/opennms/horizon/events/consumer/EventsConsumer.java
> +                LOG.warn("TenantId is empty, dropping events {}", eventLog);
LOG is needed always but can do something more when needed.

2022-11-18 17:51 UTC, cgorantla commented on events/traps/src/main/java/org/opennms/horizon/events/traps/EventCreator.java
> +        // TODO: Query inventory service for node id
yes, updated!

2022-11-18 17:51 UTC, cgorantla commented on events/consumer/src/main/java/org/opennms/horizon/events/consumer/EventsConsumer.java
> +    @Autowired
Handled!

2022-11-18 17:51 UTC, cgorantla commented on events/traps/src/main/java/org/opennms/horizon/events/traps/SyntaxToEvent.java
> +    int m_typeId;
Done!

2022-11-18 17:51 UTC, cgorantla commented on events/traps/src/main/java/org/opennms/horizon/events/traps/SyntaxToEvent.java
> +        m_syntaxToEvents = new SyntaxToEvent[] {
updated!

2022-11-18 17:51 UTC, cgorantla commented on events/traps/src/main/java/org/opennms/horizon/events/traps/TrapsConsumer.java
> +    private EventLog convertToProtoEvents(Log eventLog) {
Updated!

2022-11-21 16:58 UTC, yangli2014 commented on events/conf/src/main/java/org/opennms/horizon/events/Base64.java
> +public final class Base64 {
Do we really need our own Base64 encoder and decoder?

2022-11-21 17:17 UTC, yangli2014 commented on events/consumer/src/main/java/org/opennms/horizon/events/consumer/EventsConsumer.java
> +    private Event mapEventFromProto(org.opennms.horizon.events.proto.Event eventProto, String tenantId) {
mapstruc can save lines of code for such mapping

2022-11-21 17:20 UTC, yangli2014 commented on events/conf/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Is this conf project copied from core or horizon classic and need more task to change it? I found a lot of XML-related code.

2022-11-21 17:24 UTC, cgorantla commented on events/conf/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
We still need event conf.  This may stay this way for a while.

2022-11-21 17:28 UTC, cgorantla commented on events/conf/src/main/java/org/opennms/horizon/events/Base64.java
> +public final class Base64 {
This is coming from previous event conf utils.

2022-11-21 17:51 UTC, yangli2014 reviewed
Also, do we need so many small mvn modules under events?

2022-11-21 17:57 UTC, cgorantla commented on events/consumer/src/main/java/org/opennms/horizon/events/consumer/EventsConsumer.java
> +    private Event mapEventFromProto(org.opennms.horizon.events.proto.Event eventProto, String tenantId) {
I prefer this way unless I'm dealing with too many mappings

2022-11-21 18:04 UTC, cgorantla commented
> Also, do we need so many small mvn modules under events?

We need multiple modules for separation, IMO this is better as each module is dealing with separate task. 

There is good chance that Traps module would be moved to separate service. Then all we need is to move `traps` module.

And  `conf` is separate module that just deals with eventconf.
`consumer` is only dealing with events consumption, not traps.
`persistence` deals with all things related to tables, entities, repositories.

IMO  even  inventory service should be split into multiple maven modules, readability and code separation is better this way.

2022-11-22 20:15 UTC, geraldhumphries commented on events/conf/pom.xml
> +            src/main/java/org/opennms/horizon/events/**/*
This appears to exclude all code in this service from coverage, why? I see that it is in the `conf/pom.xml`, how does this work?

2022-11-22 20:19 UTC, cgorantla commented on events/conf/pom.xml
> +            src/main/java/org/opennms/horizon/events/**/*
Oh, does it ? I thought it will only applicable for the packages inside this maven module. I can make a targeted exclude. 
Since this module mostly have model objects for marshalling/unmarshalling xml.

2022-11-22 20:24 UTC, geraldhumphries commented on events/traps/src/main/resources/spring-beans-context.xml
> +</beans>
What about something like this?

```
@Configuration
public class SnmpHelperConfig  {
    @Bean
    public SnmpHelper snmpHelper() {
        return new SnmpHelperImpl(new Snmp4JStrategy());
    }
}
```

2022-11-22 20:28 UTC, geraldhumphries commented on events/conf/pom.xml
> +            src/main/java/org/opennms/horizon/events/**/*
I am not sure how it works with submodules, which was my question. What does this ignore? If it works how we assume and only ignores what's in this specific module, then I think it's fine.

2022-11-22 20:53 UTC, cgorantla commented on events/conf/pom.xml
> +            src/main/java/org/opennms/horizon/events/**/*
I think it only ignores in the specific module, if you look at the code coverage https://sonarcloud.io/component_measures?id=opennms_horizon-stream_events&pullRequest=465&metric=new_coverage&view=list , it lists other files from traps and consumer module.

2022-11-23 17:46 UTC, geraldhumphries commented
@cgorantla one last change, I noticed that the top-level pom in this service is named "OpenNMS Horizon :: Events :: Parent". It's a very small issue but this is used as the project name in SonarCloud. Can we rename it to just "OpenNMS Horizon :: Events", and rename `main` to "OpenNMS Horizon :: Events :: Main"?

2022-11-23 17:46 UTC, geraldhumphries approved these changes

2022-11-23 18:56 UTC, merged