HS-600 gRPC client in BFF and new GraphQL API
OpenNMS/horizon-stream pull request #466
Opened 2022-11-17 22:24 UTC by yangli2014

## Description

## Jira link(s)
- https://issues.opennms.org/browse/HS-600

## Flagged for review

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.

2022-11-18 11:09 UTC, james8hut requested changes

2022-11-18 11:13 UTC, james8hut requested changes

2022-11-18 11:13 UTC, james8hut commented on rest-server/pom.xml
> +        <mapstruct.version>1.5.3.Final</mapstruct.version>
```suggestion
```

2022-11-18 13:50 UTC, yangli2014 commented on rest-server/pom.xml
> +        <grpc.version>1.43.2</grpc.version>
This project is not using parent-pom yet. The GraphQL is not working well with Spring 2.7.X yet. I will try to use another way to integrate with parent-pom

2022-11-18 14:03 UTC, james8hut commented on rest-server/pom.xml
> +        <grpc.version>1.43.2</grpc.version>
ah ok, sorry

2022-11-18 14:35 UTC, james8hut approved these changes
LGTM

2022-11-18 15:32 UTC, yangli2014 commented on inventory/src/main/java/org/opennms/horizon/inventory/grpc/DeviceGrpcService.java
> +        responseObserver.onNext(DeviceList.newBuilder().addAllDevices(list).build());
List devices can return an empty list if there is nothing. But findById should give an error message if there isn't entity for that given id

2022-11-18 15:36 UTC, yangli2014 commented on inventory/src/main/java/org/opennms/horizon/inventory/grpc/DeviceGrpcService.java
> +            .map(nodeService::findByTenantId).orElseThrow();
I think we will add error handling when we get the tenant id from the access token since there will be more errors. Such as an invalid token.

2022-11-18 15:37 UTC, yangli2014 commented on inventory/src/main/java/org/opennms/horizon/inventory/grpc/MonitoringLocationGrpcService.java
> +
I checked the current BFF doesn't have the get all locations method. If we want we can easily add it.

2022-11-18 19:00 UTC, yangli2014 commented on inventory/src/main/java/org/opennms/horizon/inventory/grpc/MonitoringLocationGrpcService.java
> +
Actually, we have listLocations()

2022-11-21 15:02 UTC, cgorantla approved these changes
lgtm!

2022-11-21 16:20 UTC, merged