removed selector from minion-gateway-ingress.yaml
OpenNMS/horizon-stream pull request #582
Opened 2023-01-06 15:24 UTC by jaymberry

## Description

## Jira link(s)
- https://opennms.atlassian.net/browse/HS-706

## Flagged for review

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.

2023-01-06 17:36 UTC, geraldhumphries commented
Can you update this PR's description with the purpose? I assume `selector` is being removed because it's a Service resource concept, and not for Ingresses. Is that right?

2023-01-06 19:14 UTC, geraldhumphries requested changes

2023-01-06 21:48 UTC, jaymberry commented on charts/opennms/templates/opennms/minion/minion-gateway-ingress.yaml
> +  #selector:
Yes, will do that right away.

2023-01-06 21:49 UTC, jaymberry commented
> Can you update this PR's description with the purpose? I assume `selector` is being removed because it's a Service resource concept, and not for Ingresses. Is that right?

Yes, sorry, updated description and PR title.

2023-01-09 15:52 UTC, geraldhumphries approved these changes

2023-01-09 18:49 UTC, splatch approved these changes
I had initially some troubles with running it but after making proper clean start all worked as expected. One small suggestion is about marking `id.cfg` and `grpc.cfg` as examples on how to provision custom configurations into system, as these are 1:1 to what we currently include in minion image itself.

2023-01-10 03:29 UTC, merged